package com.example.entreclub.Home;

import android.util.Log;

import java.util.ArrayList;

public class checkAbuse {



//            "american\n"+
//            "anal\n"+
//            "analannie\n"+
//            "analsex\n"+
//            "angie\n"+
//            "angry\n"+
//            "anus\n"+
//            "arab\n"+
//            "arabs\n"+
//            "areola\n"+
//            "argie\n"+
//            "aroused\n"+
//            "arse\n"+
//            "arsehole\n"+
//            "asian\n"+
//            "ass\n"+
//            "assassin\n"+
//            "assassinate\n"+
//            "assassination\n"+
//            "assault\n"+
//            "assbagger\n"+
//            "assblaster\n"+
//            "assclown\n"+
//            "asscowboy\n"+
//            "asses\n"+
//            "assfuck\n"+
//            "assfucker\n"+
//            "asshat\n"+
//            "asshole\n"+
//            "assholes\n"+
//            "asshore\n"+
//            "assjockey\n"+
//            "asskiss\n"+
//            "asskisser\n"+
//            "assklown\n"+
//            "asslick\n"+
//            "asslicker\n"+
//            "asslover\n"+
//            "assman\n"+
//            "assmonkey\n"+
//            "assmunch\n"+
//            "assmuncher\n"+
//            "asspacker\n"+
//            "asspirate\n"+
//            "asspuppies\n"+
//            "assranger\n"+
//            "asswhore\n"+
//            "asswipe\n"+
//            "athletesfoot\n"+
//            "attack\n"+
//            "australian\n"+
//            "babe\n"+
//            "babies\n"+
//            "backdoor\n"+
//            "backdoorman\n"+
//            "backseat\n"+
//            "badfuck\n"+
//            "balllicker\n"+
//            "balls\n"+
//            "ballsack\n"+
//            "banging\n"+
//            "baptist\n"+
//            "barelylegal\n"+
//            "barf\n"+
//            "barface\n"+
//            "barfface\n"+
//            "bast\n"+
//            "bastard \n"+
//            "bazongas\n"+
//            "bazooms\n"+
//            "beaner\n"+
//            "beast\n"+
//            "beastality\n"+
//            "beastial\n"+
//            "beastiality\n"+
//            "beatoff\n"+
//            "beat-off\n"+
//            "beatyourmeat\n"+
//            "beaver\n"+
//            "bestial\n"+
//            "bestiality\n"+
//            "bi\n"+
//            "biatch\n"+
//            "bible\n"+
//            "bicurious\n"+
//            "bigass\n"+
//            "bigbastard\n"+
//            "bigbutt\n"+
//            "bigger\n"+
//            "bisexual\n"+
//            "bi-sexual\n"+
//            "bitch\n"+
//            "bitcher\n"+
//            "bitches\n"+
//            "bitchez\n"+
//            "bitchin\n"+
//            "bitching\n"+
//            "bitchslap\n"+
//            "bitchy\n"+
//            "biteme\n"+
//            "black\n"+
//            "blackman\n"+
//            "blackout\n"+
//            "blacks\n"+
//            "blind\n"+
//            "blow\n"+
//            "blowjob\n"+
//            "boang\n"+
//            "bogan\n"+
//            "bohunk\n"+
//            "bollick\n"+
//            "bollock\n"+
//            "bomb\n"+
//            "bombers\n"+
//            "bombing\n"+
//            "bombs\n"+
//            "bomd\n"+
//            "bondage\n"+
//            "boner\n"+
//            "bong\n"+
//            "boob\n"+
//            "boobies\n"+
//            "boobs\n"+
//            "booby\n"+
//            "boody\n"+
//            "boom\n"+
//            "boong\n"+
//            "boonga\n"+
//            "boonie\n"+
//            "booty\n"+
//            "bootycall\n"+
//            "bountybar\n"+
//            "bra\n"+
//            "brea5t\n"+
//            "breast\n"+
//            "breastjob\n"+
//            "breastlover\n"+
//            "breastman\n"+
//            "brothel\n"+
//            "bugger\n"+
//            "buggered\n"+
//            "buggery\n"+
//            "bullcrap\n"+
//            "bulldike\n"+
//            "bulldyke\n"+
//            "bullshit\n"+
//            "bumblefuck\n"+
//            "bumfuck\n"+
//            "bunga\n"+
//            "bunghole\n"+
//            "buried\n"+
//            "burn\n"+
//            "butchbabes\n"+
//            "butchdike\n"+
//            "butchdyke\n"+
//            "butt\n"+
//            "buttbang\n"+
//            "butt-bang\n"+
//            "buttface\n"+
//            "buttfuck\n"+
//            "butt-fuck\n"+
//            "buttfucker\n"+
//            "butt-fucker\n"+
//            "buttfuckers\n"+
//            "butt-fuckers\n"+
//            "butthead\n"+
//            "buttman\n"+
//            "buttmunch\n"+
//            "buttmuncher\n"+
//            "buttpirate\n"+
//            "buttplug\n"+
//            "buttstain\n"+
//            "byatch\n"+
//            "cacker\n"+
//            "cameljockey\n"+
//            "cameltoe\n"+
//            "canadian\n"+
//            "cancer\n"+
//            "carpetmuncher\n"+
//            "carruth\n"+
//            "catholic\n"+
//            "catholics\n"+
//            "cemetery\n"+
//            "chav\n"+
//            "cherrypopper\n"+
//            "chickslick\n"+
//            "children's\n"+
//            "chin\n"+
//            "chinaman\n"+
//            "chinamen\n"+
//            "chinese\n"+
//            "chink\n"+
//            "chinky\n"+
//            "choad\n"+
//            "chode\n"+
//            "christ\n"+
//            "christian\n"+
//            "church\n"+
//            "cigarette\n"+
//            "cigs\n"+
//            "clamdigger\n"+
//            "clamdiver\n"+
//            "clit\n"+
//            "clitoris\n"+
//            "clogwog\n"+
//            "cocaine\n"+
//            "cock\n"+
//            "cockblock\n"+
//            "cockblocker\n"+
//            "cockcowboy\n"+
//            "cockfight\n"+
//            "cockhead\n"+
//            "cockknob\n"+
//            "cocklicker\n"+
//            "cocklover\n"+
//            "cocknob\n"+
//            "cockqueen\n"+
//            "cockrider\n"+
//            "cocksman\n"+
//            "cocksmith\n"+
//            "cocksmoker\n"+
//            "cocksucer\n"+
//            "cocksuck \n"+
//            "cocksucked \n"+
//            "cocksucker\n"+
//            "cocksucking\n"+
//            "cocktail\n"+
//            "cocktease\n"+
//            "cocky\n"+
//            "cohee\n"+
//            "coitus\n"+
//            "color\n"+
//            "colored\n"+
//            "coloured\n"+
//            "commie\n"+
//            "communist\n"+
//            "condom\n"+
//            "conservative\n"+
//            "conspiracy\n"+
//            "coolie\n"+
//            "cooly\n"+
//            "coon\n"+
//            "coondog\n"+
//            "copulate\n"+
//            "cornhole\n"+
//            "corruption\n"+
//            "cra5h\n"+
//            "crabs\n"+
//            "crack\n"+
//            "crackpipe\n"+
//            "crackwhore\n"+
//            "crack-whore\n"+
//            "crap\n"+
//            "crapola\n"+
//            "crapper\n"+
//            "crappy\n"+
//            "crash\n"+
//            "creamy\n"+
//            "crime\n"+
//            "crimes\n"+
//            "criminal\n"+
//            "criminals\n"+
//            "crotch\n"+
//            "crotchjockey\n"+
//            "crotchmonkey\n"+
//            "crotchrot\n"+
//            "cum\n"+
//            "cumbubble\n"+
//            "cumfest\n"+
//            "cumjockey\n"+
//            "cumm\n"+
//            "cummer\n"+
//            "cumming\n"+
//            "cumquat\n"+
//            "cumqueen\n"+
//            "cumshot\n"+
//            "cunilingus\n"+
//            "cunillingus\n"+
//            "cunn\n"+
//            "cunnilingus\n"+
//            "cunntt\n"+
//            "cunt\n"+
//            "cunteyed\n"+
//            "cuntfuck\n"+
//            "cuntfucker\n"+
//            "cuntlick \n"+
//            "cuntlicker \n"+
//            "cuntlicking \n"+
//            "cuntsucker\n"+
//            "cybersex\n"+
//            "cyberslimer\n"+
//            "dago\n"+
//            "dahmer\n"+
//            "dammit\n"+
//            "damn\n"+
//            "damnation\n"+
//            "damnit\n"+
//            "darkie\n"+
//            "darky\n"+
//            "datnigga\n"+
//            "dead\n"+
//            "deapthroat\n"+
//            "death\n"+
//            "deepthroat\n"+
//            "defecate\n"+
//            "dego\n"+
//            "demon\n"+
//            "deposit\n"+
//            "desire\n"+
//            "destroy\n"+
//            "deth\n"+
//            "devil\n"+
//            "devilworshipper\n"+
//            "dick\n"+
//            "dickbrain\n"+
//            "dickforbrains\n"+
//            "dickhead\n"+
//            "dickless\n"+
//            "dicklick\n"+
//            "dicklicker\n"+
//            "dickman\n"+
//            "dickwad\n"+
//            "dickweed\n"+
//            "diddle\n"+
//            "die\n"+
//            "died\n"+
//            "dies\n"+
//            "dike\n"+
//            "dildo\n"+
//            "dingleberry\n"+
//            "dink\n"+
//            "dipshit\n"+
//            "dipstick\n"+
//            "dirty\n"+
//            "disease\n"+
//            "diseases\n"+
//            "disturbed\n"+
//            "dive\n"+
//            "dix\n"+
//            "dixiedike\n"+
//            "dixiedyke\n"+
//            "doggiestyle\n"+
//            "doggystyle\n"+
//            "dong\n"+
//            "doodoo\n"+
//            "doo-doo\n"+
//            "doom\n"+
//            "dope\n"+
//            "dragqueen\n"+
//            "dragqween\n"+
//            "dripdick\n"+
//            "drug\n"+
//            "drunk\n"+
//            "drunken\n"+
//            "dumb\n"+
//            "dumbass\n"+
//            "dumbbitch\n"+
//            "dumbfuck\n"+
//            "dyefly\n"+
//            "dyke\n"+
//            "easyslut\n"+
//            "eatballs\n"+
//            "eatme\n"+
//            "eatpussy\n"+
//            "ecstacy\n"+
//            "ejaculate\n"+
//            "ejaculated\n"+
//            "ejaculating \n"+
//            "ejaculation\n"+
//            "enema\n"+
//            "enemy\n"+
//            "erect\n"+
//            "erection\n"+
//            "ero\n"+
//            "escort\n"+
//            "ethiopian\n"+
//            "ethnic\n"+
//            "european\n"+
//            "evl\n"+
//            "excrement\n"+
//            "execute\n"+
//            "executed\n"+
//            "execution\n"+
//            "executioner\n"+
//            "explosion\n"+
//            "facefucker\n"+
//            "faeces\n"+
//            "fag\n"+
//            "fagging\n"+
//            "faggot\n"+
//            "fagot\n"+
//            "failed\n"+
//            "failure\n"+
//            "fairies\n"+
//            "fairy\n"+
//            "faith\n"+
//            "fannyfucker\n"+
//            "fart\n"+
//            "farted \n"+
//            "farting \n"+
//            "farty \n"+
//            "fastfuck\n"+
//            "fat\n"+
//            "fatah\n"+
//            "fatass\n"+
//            "fatfuck\n"+
//            "fatfucker\n"+
//            "fatso\n"+
//            "fckcum\n"+
//            "fear\n"+
//            "feces\n"+
//            "felatio \n"+
//            "felch\n"+
//            "felcher\n"+
//            "felching\n"+
//            "fellatio\n"+
//            "feltch\n"+
//            "feltcher\n"+
//            "feltching\n"+
//            "fetish\n"+
//            "fight\n"+
//            "filipina\n"+
//            "filipino\n"+
//            "fingerfood\n"+
//            "fingerfuck \n"+
//            "fingerfucked \n"+
//            "fingerfucker \n"+
//            "fingerfuckers\n"+
//            "fingerfucking \n"+
//            "fire\n"+
//            "firing\n"+
//            "fister\n"+
//            "fistfuck\n"+
//            "fistfucked \n"+
//            "fistfucker \n"+
//            "fistfucking \n"+
//            "fisting\n"+
//            "flange\n"+
//            "flasher\n"+
//            "flatulence\n"+
//            "floo\n"+
//            "flydie\n"+
//            "flydye\n"+
//            "fok\n"+
//            "fondle\n"+
//            "footaction\n"+
//            "footfuck\n"+
//            "footfucker\n"+
//            "footlicker\n"+
//            "footstar\n"+
//            "fore\n"+
//            "foreskin\n"+
//            "forni\n"+
//            "fornicate\n"+
//            "foursome\n"+
//            "fourtwenty\n"+
//            "fraud\n"+
//            "freakfuck\n"+
//            "freakyfucker\n"+
//            "freefuck\n"+
//            "fu\n"+
//            "fubar\n"+
//            "fuc\n"+
//            "fucck\n"+
//            "fuck\n"+
//            "fucka\n"+
//            "fuckable\n"+
//            "fuckbag\n"+
//            "fuckbuddy\n"+
//            "fucked\n"+
//            "fuckedup\n"+
//            "fucker\n"+
//            "fuckers\n"+
//            "fuckface\n"+
//            "fuckfest\n"+
//            "fuckfreak\n"+
//            "fuckfriend\n"+
//            "fuckhead\n"+
//            "fuckher\n"+
//            "fuckin\n"+
//            "fuckina\n"+
//            "fucking\n"+
//            "fuckingbitch\n"+
//            "fuckinnuts\n"+
//            "fuckinright\n"+
//            "fuckit\n"+
//            "fuckknob\n"+
//            "fuckme \n"+
//            "fuckmehard\n"+
//            "fuckmonkey\n"+
//            "fuckoff\n"+
//            "fuckpig\n"+
//            "fucks\n"+
//            "fucktard\n"+
//            "fuckwhore\n"+
//            "fuckyou\n"+
//            "fudgepacker\n"+
//            "fugly\n"+
//            "fuk\n"+
//            "fuks\n"+
//            "funeral\n"+
//            "funfuck\n"+
//            "fungus\n"+
//            "fuuck\n"+
//            "gangbang\n"+
//            "gangbanged \n"+
//            "gangbanger\n"+
//            "gangsta\n"+
//            "gatorbait\n"+
//            "gay\n"+
//            "gaymuthafuckinwhore\n"+
//            "gaysex \n"+
//            "geez\n"+
//            "geezer\n"+
//            "geni\n"+
//            "genital\n"+
//            "german\n"+
//            "getiton\n"+
//            "gin\n"+
//            "ginzo\n"+
//            "gipp\n"+
//            "girls\n"+
//            "givehead\n"+
//            "glazeddonut\n"+
//            "gob\n"+
//            "god\n"+
//            "godammit\n"+
//            "goddamit\n"+
//            "goddammit\n"+
//            "goddamn\n"+
//            "goddamned\n"+
//            "goddamnes\n"+
//            "goddamnit\n"+
//            "goddamnmuthafucker\n"+
//            "goldenshower\n"+
//            "gonorrehea\n"+
//            "gonzagas\n"+
//            "gook\n"+
//            "gotohell\n"+
//            "goy\n"+
//            "goyim\n"+
//            "greaseball\n"+
//            "gringo\n"+
//            "groe\n"+
//            "gross\n"+
//            "grostulation\n"+
//            "gubba\n"+
//            "gummer\n"+
//            "gun\n"+
//            "gyp\n"+
//            "gypo\n"+
//            "gypp\n"+
//            "gyppie\n"+
//            "gyppo\n"+
//            "gyppy\n"+
//            "hamas\n"+
//            "handjob\n"+
//            "hapa\n"+
//            "harder\n"+
//            "hardon\n"+
//            "harem\n"+
//            "headfuck\n"+
//            "headlights\n"+
//            "hebe\n"+
//            "heeb\n"+
//            "hell\n"+
//            "henhouse\n"+
//            "heroin\n"+
//            "herpes\n"+
//            "heterosexual\n"+
//            "hijack\n"+
//            "hijacker\n"+
//            "hijacking\n"+
//            "hillbillies\n"+
//            "hindoo\n"+
//            "hiscock\n"+
//            "hitler\n"+
//            "hitlerism\n"+
//            "hitlerist\n"+
//            "hiv\n"+
//            "ho\n"+
//            "hobo\n"+
//            "hodgie\n"+
//            "hoes\n"+
//            "hole\n"+
//            "holestuffer\n"+
//            "homicide\n"+
//            "homo\n"+
//            "homobangers\n"+
//            "homosexual\n"+
//            "honger\n"+
//            "honk\n"+
//            "honkers\n"+
//            "honkey\n"+
//            "honky\n"+
//            "hook\n"+
//            "hooker\n"+
//            "hookers\n"+
//            "hooters\n"+
//            "hore\n"+
//            "hork\n"+
//            "horn\n"+
//            "horney\n"+
//            "horniest\n"+
//            "horny\n"+
//            "horseshit\n"+
//            "hosejob\n"+
//            "hoser\n"+
//            "hostage\n"+
//            "hotdamn\n"+
//            "hotpussy\n"+
//            "hottotrot\n"+
//            "hummer\n"+
//            "husky\n"+
//            "hussy\n"+
//            "hustler\n"+
//            "hymen\n"+
//            "hymie\n"+
//            "iblowu\n"+
//            "idiot\n"+
//            "ikey\n"+
//            "illegal\n"+
//            "incest\n"+
//            "insest\n"+
//            "intercourse\n"+
//            "interracial\n"+
//            "intheass\n"+
//            "inthebuff\n"+
//            "israel\n"+
//            "israeli\n"+
//            "israel's\n"+
//            "italiano\n"+
//            "itch\n"+
//            "jackass\n"+
//            "jackoff\n"+
//            "jackshit\n"+
//            "jacktheripper\n"+
//            "jade\n"+
//            "jap\n"+
//            "japanese\n"+
//            "japcrap\n"+
//            "jebus\n"+
//            "jeez\n"+
//            "jerkoff\n"+
//            "jesus\n"+
//            "jesuschrist\n"+
//            "jew\n"+
//            "jewish\n"+
//            "jiga\n"+
//            "jigaboo\n"+
//            "jigg\n"+
//            "jigga\n"+
//            "jiggabo\n"+
//            "jigger \n"+
//            "jiggy\n"+
//            "jihad\n"+
//            "jijjiboo\n"+
//            "jimfish\n"+
//            "jism\n"+
//            "jiz \n"+
//            "jizim\n"+
//            "jizjuice\n"+
//            "jizm \n"+
//            "jizz\n"+
//            "jizzim\n"+
//            "jizzum\n"+
//            "joint\n"+
//            "juggalo\n"+
//            "jugs\n"+
//            "junglebunny\n"+
//            "kaffer\n"+
//            "kaffir\n"+
//            "kaffre\n"+
//            "kafir\n"+
//            "kanake\n"+
//            "kid\n"+
//            "kigger\n"+
//            "kike\n"+
//            "kill\n"+
//            "killed\n"+
//            "killer\n"+
//            "killing\n"+
//            "kills\n"+
//            "kink\n"+
//            "kinky\n"+
//            "kissass\n"+
//            "kkk\n"+
//            "knife\n"+
//            "knockers\n"+
//            "kock\n"+
//            "kondum\n"+
//            "koon\n"+
//            "kotex\n"+
//            "krap\n"+
//            "krappy\n"+
//            "kraut\n"+
//            "kum\n"+
//            "kumbubble\n"+
//            "kumbullbe\n"+
//            "kummer\n"+
//            "kumming\n"+
//            "kumquat\n"+
//            "kums\n"+
//            "kunilingus\n"+
//            "kunnilingus\n"+
//            "kunt\n"+
//            "ky\n"+
//            "kyke\n"+
//            "lactate\n"+
//            "laid\n"+
//            "lapdance\n"+
//            "latin\n"+
//            "lesbain\n"+
//            "lesbayn\n"+
//            "lesbian\n"+
//            "lesbin\n"+
//            "lesbo\n"+
//            "lez\n"+
//            "lezbe\n"+
//            "lezbefriends\n"+
//            "lezbo\n"+
//            "lezz\n"+
//            "lezzo\n"+
//            "liberal\n"+
//            "libido\n"+
//            "licker\n"+
//            "lickme\n"+
//            "lies\n"+
//            "limey\n"+
//            "limpdick\n"+
//            "limy\n"+
//            "lingerie\n"+
//            "liquor\n"+
//            "livesex\n"+
//            "loadedgun\n"+
//            "lolita\n"+
//            "looser\n"+
//            "loser\n"+
//            "lotion\n"+
//            "lovebone\n"+
//            "lovegoo\n"+
//            "lovegun\n"+
//            "lovejuice\n"+
//            "lovemuscle\n"+
//            "lovepistol\n"+
//            "loverocket\n"+
//            "lowlife\n"+
//            "lsd\n"+
//            "lubejob\n"+
//            "lucifer\n"+
//            "luckycammeltoe\n"+
//            "lugan\n"+
//            "lynch\n"+
//            "macaca\n"+
//            "mad\n"+
//            "mafia\n"+
//            "magicwand\n"+
//            "mams\n"+
//            "manhater\n"+
//            "manpaste\n"+
//            "marijuana\n"+
//            "mastabate\n"+
//            "mastabater\n"+
//            "masterbate\n"+
//            "masterblaster\n"+
//            "mastrabator\n"+
//            "masturbate\n"+
//            "masturbating\n"+
//            "mattressprincess\n"+
//            "meatbeatter\n"+
//            "meatrack\n"+
//            "meth\n"+
//            "mexican\n"+
//            "mgger\n"+
//            "mggor\n"+
//            "mickeyfinn\n"+
//            "mideast\n"+
//            "milf\n"+
//            "minority\n"+
//            "mockey\n"+
//            "mockie\n"+
//            "mocky\n"+
//            "mofo\n"+
//            "moky\n"+
//            "moles\n"+
//            "molest\n"+
//            "molestation\n"+
//            "molester\n"+
//            "molestor\n"+
//            "moneyshot\n"+
//            "mooncricket\n"+
//            "mormon\n"+
//            "moron\n"+
//            "moslem\n"+
//            "mosshead\n"+
//            "mothafuck\n"+
//            "mothafucka\n"+
//            "mothafuckaz\n"+
//            "mothafucked \n"+
//            "mothafucker\n"+
//            "mothafuckin\n"+
//            "mothafucking \n"+
//            "mothafuckings\n"+
//            "motherfuck\n"+
//            "motherfucked\n"+
//            "motherfucker\n"+
//            "motherfuckin\n"+
//            "motherfucking\n"+
//            "motherfuckings\n"+
//            "motherlovebone\n"+
//            "muff\n"+
//            "muffdive\n"+
//            "muffdiver\n"+
//            "muffindiver\n"+
//            "mufflikcer\n"+
//            "mulatto\n"+
//            "muncher\n"+
//            "munt\n"+
//            "murder\n"+
//            "murderer\n"+
//            "muslim\n"+
//            "naked\n"+
//            "narcotic\n"+
//            "nasty\n"+
//            "nastybitch\n"+
//            "nastyho\n"+
//            "nastyslut\n"+
//            "nastywhore\n"+
//            "nazi\n"+
//            "necro\n"+
//            "negro\n"+
//            "negroes\n"+
//            "negroid\n"+
//            "negro's\n"+
//            "nig\n"+
//            "niger\n"+
//            "nigerian\n"+
//            "nigerians\n"+
//            "nigg\n"+
//            "nigga\n"+
//            "niggah\n"+
//            "niggaracci\n"+
//            "niggard\n"+
//            "niggarded\n"+
//            "niggarding\n"+
//            "niggardliness\n"+
//            "niggardliness's\n"+
//            "niggardly\n"+
//            "niggards\n"+
//            "niggard's\n"+
//            "niggaz\n"+
//            "nigger\n"+
//            "niggerhead\n"+
//            "niggerhole\n"+
//            "niggers\n"+
//            "nigger's\n"+
//            "niggle\n"+
//            "niggled\n"+
//            "niggles\n"+
//            "niggling\n"+
//            "nigglings\n"+
//            "niggor\n"+
//            "niggur\n"+
//            "niglet\n"+
//            "nignog\n"+
//            "nigr\n"+
//            "nigra\n"+
//            "nigre\n"+
//            "nip\n"+
//            "nipple\n"+
//            "nipplering\n"+
//            "nittit\n"+
//            "nlgger\n"+
//            "nlggor\n"+
//            "nofuckingway\n"+
//            "nook\n"+
//            "nookey\n"+
//            "nookie\n"+
//            "noonan\n"+
//            "nooner\n"+
//            "nude\n"+
//            "nudger\n"+
//            "nuke\n"+
//            "nutfucker\n"+
//            "nymph\n"+
//            "ontherag\n"+
//            "oral\n"+
//            "orga\n"+
//            "orgasim \n"+
//            "orgasm\n"+
//            "orgies\n"+
//            "orgy\n"+
//            "osama\n"+
//            "paki\n"+
//            "palesimian\n"+
//            "palestinian\n"+
//            "pansies\n"+
//            "pansy\n"+
//            "panti\n"+
//            "panties\n"+
//            "payo\n"+
//            "pearlnecklace\n"+
//            "peck\n"+
//            "pecker\n"+
//            "peckerwood\n"+
//            "pee\n"+
//            "peehole\n"+
//            "pee-pee\n"+
//            "peepshow\n"+
//            "peepshpw\n"+
//            "pendy\n"+
//            "penetration\n"+
//            "peni5\n"+
//            "penile\n"+
//            "penis\n"+
//            "penises\n"+
//            "penthouse\n"+
//            "period\n"+
//            "perv\n"+
//            "phonesex\n"+
//            "phuk\n"+
//            "phuked\n"+
//            "phuking\n"+
//            "phukked\n"+
//            "phukking\n"+
//            "phungky\n"+
//            "phuq\n"+
//            "pi55\n"+
//            "picaninny\n"+
//            "piccaninny\n"+
//            "pickaninny\n"+
//            "piker\n"+
//            "pikey\n"+
//            "piky\n"+
//            "pimp\n"+
//            "pimped\n"+
//            "pimper\n"+
//            "pimpjuic\n"+
//            "pimpjuice\n"+
//            "pimpsimp\n"+
//            "pindick\n"+
//            "piss\n"+
//            "pissed\n"+
//            "pisser\n"+
//            "pisses \n"+
//            "pisshead\n"+
//            "pissin \n"+
//            "pissing\n"+
//            "pissoff \n"+
//            "pistol\n"+
//            "pixie\n"+
//            "pixy\n"+
//            "playboy\n"+
//            "playgirl\n"+
//            "pocha\n"+
//            "pocho\n"+
//            "pocketpool\n"+
//            "pohm\n"+
//            "polack\n"+
//            "pom\n"+
//            "pommie\n"+
//            "pommy\n"+
//            "poo\n"+
//            "poon\n"+
//            "poontang\n"+
//            "poop\n"+
//            "pooper\n"+
//            "pooperscooper\n"+
//            "pooping\n"+
//            "poorwhitetrash\n"+
//            "popimp\n"+
//            "porchmonkey\n"+
//            "porn\n"+
//            "pornflick\n"+
//            "pornking\n"+
//            "porno\n"+
//            "pornography\n"+
//            "pornprincess\n"+
//            "pot\n"+
//            "poverty\n"+
//            "premature\n"+
//            "pric\n"+
//            "prick\n"+
//            "prickhead\n"+
//            "primetime\n"+
//            "propaganda\n"+
//            "pros\n"+
//            "prostitute\n"+
//            "protestant\n"+
//            "pu55i\n"+
//            "pu55y\n"+
//            "pube\n"+
//            "pubic\n"+
//            "pubiclice\n"+
//            "pud\n"+
//            "pudboy\n"+
//            "pudd\n"+
//            "puddboy\n"+
//            "puke\n"+
//            "puntang\n"+
//            "purinapricness\n"+
//            "puss\n"+
//            "pussie\n"+
//            "pussies\n"+
//            "pussy\n"+
//            "pussycat\n"+
//            "pussyeater\n"+
//            "pussyfucker\n"+
//            "pussylicker\n"+
//            "pussylips\n"+
//            "pussylover\n"+
//            "pussypounder\n"+
//            "pusy\n"+
//            "quashie\n"+
//            "queef\n"+
//            "queer\n"+
//            "quickie\n"+
//            "quim\n"+
//            "ra8s\n"+
//            "rabbi\n"+
//            "racial\n"+
//            "racist\n"+
//            "radical\n"+
//            "radicals\n"+
//            "raghead\n"+
//            "randy\n"+
//            "rape\n"+
//            "raped\n"+
//            "raper\n"+
//            "rapist\n"+
//            "rearend\n"+
//            "rearentry\n"+
//            "rectum\n"+
//            "redlight\n"+
//            "redneck\n"+
//            "reefer\n"+
//            "reestie\n"+
//            "refugee\n"+
//            "reject\n"+
//            "remains\n"+
//            "rentafuck\n"+
//            "republican\n"+
//            "rere\n"+
//            "retard\n"+
//            "retarded\n"+
//            "ribbed\n"+
//            "rigger\n"+
//            "rimjob\n"+
//            "rimming\n"+
//            "roach\n"+
//            "robber\n"+
//            "roundeye\n"+
//            "rump\n"+
//            "russki\n"+
//            "russkie\n"+
//            "sadis\n"+
//            "sadom\n"+
//            "samckdaddy\n"+
//            "sandm\n"+
//            "sandnigger\n"+
//            "satan\n"+
//            "scag\n"+
//            "scallywag\n"+
//            "scat\n"+
//            "schlong\n"+
//            "screw\n"+
//            "screwyou\n"+
//            "scrotum\n"+
//            "scum\n"+
//            "semen\n"+
//            "seppo\n"+
//            "servant\n"+
//            "sex\n"+
//            "sexed\n"+
//            "sexfarm\n"+
//            "sexhound\n"+
//            "sexhouse\n"+
//            "sexing\n"+
//            "sexkitten\n"+
//            "sexpot\n"+
//            "sexslave\n"+
//            "sextogo\n"+
//            "sextoy\n"+
//            "sextoys\n"+
//            "sexual\n"+
//            "sexually\n"+
//            "sexwhore\n"+
//            "sexy\n"+
//            "sexymoma\n"+
//            "sexy-slim\n"+
//            "shag\n"+
//            "shaggin\n"+
//            "shagging\n"+
//            "shat\n"+
//            "shav\n"+
//            "shawtypimp\n"+
//            "sheeney\n"+
//            "shhit\n"+
//            "shinola\n"+
//            "shit\n"+
//            "shitcan\n"+
//            "shitdick\n"+
//            "shite\n"+
//            "shiteater\n"+
//            "shited\n"+
//            "shitface\n"+
//            "shitfaced\n"+
//            "shitfit\n"+
//            "shitforbrains\n"+
//            "shitfuck\n"+
//            "shitfucker\n"+
//            "shitfull\n"+
//            "shithapens\n"+
//            "shithappens\n"+
//            "shithead\n"+
//            "shithouse\n"+
//            "shiting\n"+
//            "shitlist\n"+
//            "shitola\n"+
//            "shitoutofluck\n"+
//            "shits\n"+
//            "shitstain\n"+
//            "shitted\n"+
//            "shitter\n"+
//            "shitting\n"+
//            "shitty \n"+
//            "shoot\n"+
//            "shooting\n"+
//            "shortfuck\n"+
//            "showtime\n"+
//            "sick\n"+
//            "sissy\n"+
//            "sixsixsix\n"+
//            "sixtynine\n"+
//            "sixtyniner\n"+
//            "skank\n"+
//            "skankbitch\n"+
//            "skankfuck\n"+
//            "skankwhore\n"+
//            "skanky\n"+
//            "skankybitch\n"+
//            "skankywhore\n"+
//            "skinflute\n"+
//            "skum\n"+
//            "skumbag\n"+
//            "slant\n"+
//            "slanteye\n"+
//            "slapper\n"+
//            "slaughter\n"+
//            "slav\n"+
//            "slave\n"+
//            "slavedriver\n"+
//            "sleezebag\n"+
//            "sleezeball\n"+
//            "slideitin\n"+
//            "slime\n"+
//            "slimeball\n"+
//            "slimebucket\n"+
//            "slopehead\n"+
//            "slopey\n"+
//            "slopy\n"+
//            "slut\n"+
//            "sluts\n"+
//            "slutt\n"+
//            "slutting\n"+
//            "slutty\n"+
//            "slutwear\n"+
//            "slutwhore\n"+
//            "smack\n"+
//            "smackthemonkey\n"+
//            "smut\n"+
//            "snatch\n"+
//            "snatchpatch\n"+
//            "snigger\n"+
//            "sniggered\n"+
//            "sniggering\n"+
//            "sniggers\n"+
//            "snigger's\n"+
//            "sniper\n"+
//            "snot\n"+
//            "snowback\n"+
//            "snownigger\n"+
//            "sob\n"+
//            "sodom\n"+
//            "sodomise\n"+
//            "sodomite\n"+
//            "sodomize\n"+
//            "sodomy\n"+
//            "sonofabitch\n"+
//            "sonofbitch\n"+
//            "sooty\n"+
//            "sos\n"+
//            "soviet\n"+
//            "spaghettibender\n"+
//            "spaghettinigger\n"+
//            "spank\n"+
//            "spankthemonkey\n"+
//            "sperm\n"+
//            "spermacide\n"+
//            "spermbag\n"+
//            "spermhearder\n"+
//            "spermherder\n"+
//            "spic\n"+
//            "spick\n"+
//            "spig\n"+
//            "spigotty\n"+
//            "spik\n"+
//            "spit\n"+
//            "spitter\n"+
//            "splittail\n"+
//            "spooge\n"+
//            "spreadeagle\n"+
//            "spunk\n"+
//            "spunky\n"+
//            "squaw\n"+
//            "stagg\n"+
//            "stiffy\n"+
//            "strapon\n"+
//            "stringer\n"+
//            "stripclub\n"+
//            "stroke\n"+
//            "stroking\n"+
//            "stupid\n"+
//            "stupidfuck\n"+
//            "stupidfucker\n"+
//            "suck\n"+
//            "suckdick\n"+
//            "sucker\n"+
//            "suckme\n"+
//            "suckmyass\n"+
//            "suckmydick\n"+
//            "suckmytit\n"+
//            "suckoff\n"+
//            "suicide\n"+
//            "swallow\n"+
//            "swallower\n"+
//            "swalow\n"+
//            "swastika\n"+
//            "sweetness\n"+
//            "syphilis\n"+
//            "taboo\n"+
//            "taff\n"+
//            "tampon\n"+
//            "tang\n"+
//            "tantra\n"+
//            "tarbaby\n"+
//            "tard\n"+
//            "teat\n"+
//            "terror\n"+
//            "terrorist\n"+
//            "teste\n"+
//            "testicle\n"+
//            "testicles\n"+
//            "thicklips\n"+
//            "thirdeye\n"+
//            "thirdleg\n"+
//            "threesome\n"+
//            "threeway\n"+
//            "timbernigger\n"+
//            "tinkle\n"+
//            "tit\n"+
//            "titbitnipply\n"+
//            "titfuck\n"+
//            "titfucker\n"+
//            "titfuckin\n"+
//            "titjob\n"+
//            "titlicker\n"+
//            "titlover\n"+
//            "tits\n"+
//            "tittie\n"+
//            "titties\n"+
//            "titty\n"+
//            "tnt\n"+
//            "toilet\n"+
//            "tongethruster\n"+
//            "tongue\n"+
//            "tonguethrust\n"+
//            "tonguetramp\n"+
//            "tortur\n"+
//            "torture\n"+
//            "tosser\n"+
//            "towelhead\n"+
//            "trailertrash\n"+
//            "tramp\n"+
//            "trannie\n"+
//            "tranny\n"+
//            "transexual\n"+
//            "transsexual\n"+
//            "transvestite\n"+
//            "triplex\n"+
//            "trisexual\n"+
//            "trojan\n"+
//            "trots\n"+
//            "tuckahoe\n"+
//            "tunneloflove\n"+
//            "turd\n"+
//            "turnon\n"+
//            "twat\n"+
//            "twink\n"+
//            "twinkie\n"+
//            "twobitwhore\n"+
//            "uck\n"+
//            "uk\n"+
//            "unfuckable\n"+
//            "upskirt\n"+
//            "uptheass\n"+
//            "upthebutt\n"+
//            "urinary\n"+
//            "urinate\n"+
//            "urine\n"+
//            "usama\n"+
//            "uterus\n"+
//            "vagina\n"+
//            "vaginal\n"+
//            "vatican\n"+
//            "vibr\n"+
//            "vibrater\n"+
//            "vibrator\n"+
//            "vietcong\n"+
//            "violence\n"+
//            "virgin\n"+
//            "virginbreaker\n"+
//            "vomit\n"+
//            "vulva\n"+
//            "wab\n"+
//            "wank\n"+
//            "wanker\n"+
//            "wanking\n"+
//            "waysted\n"+
//            "weapon\n"+
//            "weenie\n"+
//            "weewee\n"+
//            "welcher\n"+
//            "welfare\n"+
//            "wetb\n"+
//            "wetback\n"+
//            "wetspot\n"+
//            "whacker\n"+
//            "whash\n"+
//            "whigger\n"+
//            "whiskey\n"+
//            "whiskeydick\n"+
//            "whiskydick\n"+
//            "whit\n"+
//            "whitenigger\n"+
//            "whites\n"+
//            "whitetrash\n"+
//            "whitey\n"+
//            "whiz\n"+
//            "whop\n"+
//            "whore\n"+
//            "whorefucker\n"+
//            "whorehouse\n"+
//            "wigger\n"+
//            "willie\n"+
//            "williewanker\n"+
//            "willy\n"+
//            "wn\n"+
//            "wog\n"+
//            "women's\n"+
//            "wop\n"+
//            "wtf\n"+
//            "wuss\n"+
//            "wuzzie\n"+
//            "xtc\n"+
//            "xxx\n"+
//            "yankee\n"+
//            "yellowman\n"+
//            "zigabo\n"+
//            "zipperhead\n";
}
